/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: naira001 (https://sketchfab.com/naira001)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/numbers-f4febd1a64c44395a33780f70c05bd80
Title: Numbers
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import numbersScene  from "../assets/3d/numbers.glb"
export function Numbers(props) {
  const { nodes, materials } = useGLTF(numbersScene);
 // console.log("NODS" +JSON.stringify(nodes))
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}
      position={[1, 1, 1]}
      >
          
        
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.numbers2_numbers1_0.geometry}
          material={materials.numbers1}
        />
       <mesh
          castShadow
          receiveShadow
          geometry={nodes.numbers2_numbers1_0_1.geometry}
          material={materials.numbers1}
  /> 
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N6_numbers1_0.geometry}
          material={materials.numbers1}
          position={[78.667, 56.25, 0]}
          rotation={[0, 0, -Math.PI]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/numbers.glb");