/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: akhmadievjonas90 (https://sketchfab.com/akhmadievjonas90)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tank-tower-kv-1-low-poly-f3727c8950f7402e88b6b376050e82c1
Title: Tank tower KV-1 Low-poly
*/



/*
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import towerScene from "../assets/3d/tank_tower_kv-1_low-poly.glb"
export function Tower(props) {

    const {outlook} = props
  const { nodes, materials } = useGLTF(towerScene)
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.KV_1_BashNya_low001_Material_0.geometry}
        material={materials.Material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  )
}

useGLTF.preload('../assets/3d/tank_tower_kv-1_low-poly.glb')


 */



import React, { useRef, useEffect, useMemo } from 'react';
import { useGLTF, useTexture } from '@react-three/drei';
import { MeshBasicMaterial } from 'three';
import towerScene from '../assets/3d/tank_tower_kv-1_low-poly.glb';

export function Tower({ outlook }) {
  const { nodes, materials } = useGLTF(towerScene);
  const texture = useTexture(outlook.texture ||
    // 'https://example.com/default_texture.jpg'
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTEOajyiyvLQuaogfSh4C1_1tZDXEE83OMfg&s"
    );
  const newMaterial = useRef();

  useEffect(() => {
    if (!newMaterial.current) {
      newMaterial.current = new MeshBasicMaterial({ map: texture });
    } else {
      newMaterial.current.map = texture;
    }
  }, [texture]);

  const materialKey = useMemo(() => {
    return outlook.texture ? `${outlook.texture}_${texture.uuid}` : null;
  }, [outlook.texture, texture.uuid]);

  if (materialKey) {
    materials.Material = newMaterial.current;
  }

  return (
    <group dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.KV_1_BashNya_low001_Material_0.geometry}
        material={materials.Material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload('../assets/3d/tank_tower_kv-1_low-poly.glb');
