/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: digitalnutsome (https://sketchfab.com/digitalnutsome)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rubins-vase-the-two-face-one-vase-illusion-4d04782629f540779f5a7c9690f73d8e
Title: Rubin's vase ("The Two Face, One Vase Illusion")
*/



/*
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import VaseScene from "../assets/3d/rubins_vase_the_two_face_one_vase_illusion.glb"
const  Vase =(props) => {
  const { nodes, materials } = useGLTF(VaseScene)
 
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.simple}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={4.5}
      />
    </group>
  )
}

//useGLTF.preload('/rubins_vase_the_two_face_one_vase_illusion.glb')

export default Vase

*/


import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import VaseScene from "../assets/3d/rubins_vase_the_two_face_one_vase_illusion.glb"
//import ManScene from "../assets/3d/business_man_standing.glb"
export function Vase(props) {
  const { nodes, materials } = useGLTF(VaseScene);
  const { scene, animations } = useGLTF(VaseScene);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.simple}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={4.5}
      />
    </group>
  );
}
useGLTF.preload("/business_man_standing.glb");